// <auto-generated />
namespace Depcom.TaberIsla.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_bajas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_bajas));
        
        string IMigrationMetadata.Id
        {
            get { return "201611251901386_add_bajas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
