// <auto-generated />
namespace Depcom.TaberIsla.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class auditoria_y_campo_de_eespecial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(auditoria_y_campo_de_eespecial));
        
        string IMigrationMetadata.Id
        {
            get { return "201610302207460_auditoria_y_campo_de_eespecial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
